version: "3"

services:
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/assets/node_modules
      - /app/_build
      - /app/deps

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    logging:
      driver: "none"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: qwerty
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

volumes:
  db:
  pgadmin:
